[book]
authors = ["leklachu"]
language = "en"
multilingual = false
src = "src"
title = "Philosophical Discourses between a Lion and a Lamb"

[build]
build-dir = "docs"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
curly-quotes = true
